CREATE TABLE chat (
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  chat_id CHARACTER VARYING(255) NOT NULL,
  mensagem TEXT NOT NULL,
  tipo_mensagem CHARACTER VARYING(10) NOT NULL,
  data_criacao TIMESTAMP NOT NULL
);
